choice_site/choice_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('choicemaster.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
]

choice_site/choicemaster/urls.py
from django.conf.urls import url
from . import views, ajax

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/question/$', views.add_question, name='add_question'),
    url(r'^suggestion/redirect/$', views.redirect_suggestion,
        name='Suggestion'),

    url(r'^report/$', views.report, name='report'),
    url(r'^suggestions/$', views.suggestions, name='suggestions'),

    url(r'ajax/get_quantity_suggestions/$',
        ajax.get_quantity_suggestions,
        name='get_quantity_suggestions'),
    url(r'ajax_view/$', ajax.ajax_view, name='ajax_view'),
    url(r'^ajax/delete/report$', ajax.delete_report, name="delete_report"),
    url(r'^ajax/delete/question/$', ajax.delete_question,
        name="delete_question"),
    url(r'^ajax/delete/answer/$', ajax.delete_answer, name="delete_answer"),
    url(r'^ajax/edit/question/$', ajax.edit_question, name="edit_question"),
    url(r'^ajax/edit/answer/$', ajax.edit_ans, name="edit_answer"),
    url(r'^ajax/get_correct/$', ajax.get_correct, name='get_correct'),
    url(r'^ajax/edit/autoreport/$', ajax.autoreport, name='autoreport'),
    url(r'^ajax/edit/reporting/$', ajax.add_report, name='add_report'),
    url(r'^ajax/edit/correct/$', ajax.edit_correct, name='edit_correct'),
    url(r'^ajax/accept/suggestion/$', ajax.accept_suggestion,
        name='accept_suggestion'),

    url(r'^configure1/$', views.configure_exam1, name='configure_exam1'),
    url(r'^configure2/(?P<exam_id>[0-9]+)/$', views.configure_exam2,
        name='configure_exam2'),
    url(r'^configure3/(?P<exam_id>[0-9]+)/$', views.configure_exam3,
        name='configure_exam3'),

    url(r'^resolve_exam/$', views.resolve_exam, name='resolve_exam'),
    url(r'^resolve_exam/(?P<exam_id>[0-9]+)/$', views.resolve_exam,
        name='resolve_exam'),

    url(r'^statistics/subjects/$', views.subjects_statistics,
        name='subject_statistics'),
    url(r'^statistics/subject/(?P<subject_id>[0-9]+)/$', views.subject_detail,
        name='exam_detail'),
    url(r'^statistics/exam/(?P<exam_id>[0-9]+)/$', views.exam_detail,
        name='exam_detail'),

    url(r'^ajax/suggestion/send/$', ajax.suggestion, name='Send suggestion')
]

choice_site/choicemaster/forms.py
from django import forms
from .models import Subject, Topic, Answer
from django.core.validators import MinValueValidator, MaxValueValidator

import customWidget


def get_topics(ids):
    """
    Get sorted list of topics from the given ID
    :param request: str
    :return: list
    """
    topics = Topic.objects.filter(subject_id=ids)
    choices = dict()
    for t in topics:
        choices[str(t.id)] = t.topic_title
    choices = sorted(choices.items())
    return choices


class SubjectForm(forms.ModelForm):
    subject = forms.ModelChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.Select(
            attrs={
                'onchange': 'form.submit();'}))

    class Meta:
        model = Subject
        exclude = [
            'subject_title',
            'subject_description',
            'subject_department']


class MultipleTopicForm(forms.ModelForm):
    topic = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(),
        required=False,
        widget=customWidget.CheckboxSelectMultiple)

    def __init__(self, ids, *args, **kwargs):
        super(MultipleTopicForm, self).__init__(*args, **kwargs)
        self.fields['topic'].queryset = Topic.objects.filter(subject_id=ids)

    class Meta:
        model = Topic
        exclude = ['subject', 'topic_title', 'topic_description']


ALGORITHMS = (('0', 'Based on errors'), ('1', 'Random'))


class ConfigForm(forms.Form):
    quantity = forms.IntegerField(label="Quantity of questions to solve:")
    timer = forms.IntegerField(validators=[MinValueValidator(5),
                                           MaxValueValidator(120)],
                               help_text="Input in seconds",
                               label="Write the amount of time per question "
                                     "required:")
    algorithm = forms.ChoiceField(choices=ALGORITHMS, label="Choose an "
                                                            "algorithm:")

    def __init__(self, max_quantity, *args, **kwargs):
        super(ConfigForm, self).__init__(*args, **kwargs)
        self.fields['quantity'].validators =\
            [MaxValueValidator(max_quantity)]


class ExamForm(forms.ModelForm):

    answer = forms.ModelChoiceField(required=True, widget=forms.RadioSelect,
                                    queryset=Answer.objects.all())

    class Meta:
        model = Answer
        exclude = ['question', 'correct']

    def __init__(self, *args, **kwargs):
        question_id = None
        if kwargs:
            question_id = kwargs.pop('question')
        super(ExamForm, self).__init__(*args, **kwargs)
        if question_id:
            self.fields['answer'].queryset = Answer.objects.filter(
                question=question_id)
        else:
            self.fields['answer'].queryset = Answer.objects.filter(question=0)


TOPICS = (('0', 'Select Topic'), ('1', '---'))


class UploadQuestionForm(forms.Form):
    subject = forms.ModelChoiceField(required=True,
                                     widget=forms.Select(attrs={'onchange':
                                                                'get_topics('
                                                                ');'}),
                                     queryset=Subject.objects.all())
    topic = forms.ChoiceField(choices=TOPICS)
    xmlfile = forms.FileField(label='Choose XML file')


class SuggestQuestionForm(forms.Form):
    subject = forms.ModelChoiceField(required=True,
                                     widget=forms.Select(attrs={'onchange':
                                                                'get_topics('
                                                                ');'}),
                                     queryset=Subject.objects.all())
    topic = forms.ChoiceField(choices=TOPICS)

choice_site/choicemaster/views.py
import sys
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from choicemaster import models
from .forms import *
from django.http.response import HttpResponse
from .upload import parse_xml_question
from .exam_functions import get_question, get_mistakes
from .models import Report, Question, Answer, Subject
from graphos.sources.simple import SimpleDataSource
from graphos.renderers.gchart import LineChart
import json


@login_required
def index(request, message=''):
    """
    Simple index view that renders a message passed by some request and
    returns it as a HTML response
    :param request: Request, str
    :return: View
    """
    if message:
        context = {'message': message}
    else:
        context = {'message': 'Everything ok!'}
    context['reported'] = Report.objects.exclude(report_state='E').count()

    return render(request, 'choicemaster/index.html', context)


def redirect_suggestion(request):
    context = {'message': 'Suggestion submitted successfully'}
    return render(request, 'choicemaster/index.html', context)


@login_required
def add_question(request):
    """
    Get the list of available subjects from request and return them rendered
    as a response with the corresponding template
    :param request: Request
    :return: View
    """
    context = dict()
    if request.user.is_staff:
        if request.method == 'POST':
            form = UploadQuestionForm(request.POST, request.FILES)
            # if form.is_valid():
            topic = request.POST.get('topic')
            file = request.FILES['xmlfile']
            if topic > 0:
                result = parse_xml_question(file, topic)
                if result['status']:
                    return redirect('index')
                else:
                    form = UploadQuestionForm()
        else:
            form = UploadQuestionForm()
            context['form'] = form

        return render(request, 'choicemaster/add/question.html', context)

    else:
        form = SuggestQuestionForm()
        context['form'] = form
        return render(request, 'choicemaster/add/suggestion.html', context)


def report(request):
    """
    Pass on to the reports template, the number of reports not evaluated so far
    :param request: Request
    :return: View
    """
    context = dict()
    context['reports'] = Report.objects.exclude(report_state="E")
    return render(request, 'choicemaster/report.html', context)


def suggestions(request):
    """
    Pass on to the suggested questions template, the number of questions
    suggested so far
    :param request: Request
    :return: View
    """
    context = dict()
    context['questions'] = models.Question.objects.filter(available=False)
    return render(request, 'choicemaster/suggestions.html', context)


# Nuevos configure
@login_required
def configure_exam1(request):
    """
    First view regarding an exam configuration. Look for a form from the input
    request. Retrieve the subject from the POST data and create an exam
    instance related to the user to redirect it to the template in which he
    chooses the topics he wants to include in the exam
    :param request: Request
    :return: View
    """
    if request.method == 'POST':
        user = None
        if request.user.is_authenticated():
            user = request.user
        form = SubjectForm(request.POST)
        if form.is_valid():
            subject_id = request.POST.get('subject')
            exam = models.Exam(user=user)
            exam.subject = models.Subject.objects.get(pk=subject_id)
            exam.save()
            return redirect('configure_exam2', exam_id=exam.id)
    else:
        form = SubjectForm()
        return render(request, 'choicemaster/exam/configure_exam1.html',
                      {'form': form})


@login_required
def configure_exam2(request, exam_id):
    """
    Get a list of topics from request and include them in the exam given by
    exam_id. Save it in the exam object and redirect it to the next exam
    configuration template
    :param request: Request, str
    :return: View
    """
    e = models.Exam.objects.get(pk=exam_id)
    if not e.closed:
        ids = e.subject.id
        context = dict()
        context['subject_text'] = e.subject.subject_title
        context['exam_id'] = exam_id
        if request.method == 'POST':
            form = MultipleTopicForm(ids, request.POST)
            if form.is_valid():
                topic_ids = request.POST.getlist('topic')
                for idt in topic_ids:
                    t = models.Topic.objects.get(pk=idt)
                    e.topic.add(t)
                e.save()
                return redirect('configure_exam3', exam_id=exam_id)
        else:
            form = MultipleTopicForm(e.subject.id)

        context['form'] = form
        return render(
            request,
            'choicemaster/exam/configure_exam2.html',
            context)
    else:
        message = "You have already taken that exam." \
            + "Please create a new one from the 'Take an exam' section"
        return render(request, 'choicemaster/index.html', {'message': message})


@login_required
def configure_exam3(request, exam_id):
    """
    Add questions to the exam object according to the number required by the
    user. Raise an error message in case the required number of questions is
    greater than the number of questions available in the database for such
    subject
    :param request: Request, str
    :return: View
    """
    e = models.Exam.objects.get(pk=exam_id)
    if not e.closed:
        max_quantity = 0
        context = dict()
        context['subject_text'] = e.subject.subject_title
        context['exam_id'] = exam_id
        context['topics'] = e.topic.all()

        for t in e.topic.all():
            questions = models.Question.objects.filter(
                topic=t.id, available=True)
            max_quantity += len(questions)
        if request.method == 'POST':
            form = ConfigForm(max_quantity, request.POST)
            if form.is_valid():
                quantity = request.POST.get('quantity')
                timer = request.POST.get('timer')
                algorithm = request.POST.get('algorithm')
                e = models.Exam.objects.get(pk=exam_id)
                e.exam_quantity_questions = quantity
                e.remaining = quantity
                e.exam_timer = timer
                e.exam_algorithm = algorithm
                e.save()
                return redirect('resolve_exam', exam_id=exam_id)
        else:
            if max_quantity > 0:
                form = ConfigForm(max_quantity)
                context['form'] = form
                return render(
                    request,
                    'choicemaster/exam/configure_exam3.html',
                    context)
            else:
                message = "Sorry there are not questions about those topics" \
                          "yet! We invite you to suggest some on the Suggest" \
                          " a question section"
                return render(request,
                              'choicemaster/index.html',
                              {'message': message})

    else:
        message = "You have already taken that exam." \
            + " Please create a new one from the 'Take an exam' section"
        return render(request, 'choicemaster/index.html', {'message': message})


def get_first(iterable, default=None):
    if iterable:
        for item in iterable:
            return item
    return default


def resolve_exam(request, exam_id=''):
    """
    View to actually solve the exam. Consider two cases:
    1. request has been sent for the first time on this exam, in which case it
    contains the information about the exam settings (subject, timer, quantity,
    algorithm). Generate an ExamView for such settings, fill the exam object
    with questions and then choose the first question from the first topic in
    order to display it in the resolve_exam template

    2. request method is POST, which means it has been triggered by a solution
    submitted in the front end. Check whether the answer given by the user is
    right or wrong to keep a record to be used in the algorithm to display
    questions afterwards. Also, keep track of remaining time and use it to pass
    to the next question in case it is over.
    :param request: Request, str
    :return: View
    """
    if request.method != 'POST':
        exam = models.Exam.objects.get(pk=exam_id)
        if not exam.closed:
            subject = exam.subject
            timer = exam.exam_timer
            algorithm = exam.exam_algorithm
            topic_ids = exam.topic.all()  # TODO
            mistakes = {}
            # We store all the questions of the selected topics
            for item in topic_ids:
                questions_tmp = models.Question.objects.filter(
                    topic=models.Topic
                    .objects
                    .get(pk=item.id),
                    available=True)
                mistakes[str(item.id)] = 0
                for q in questions_tmp:
                    exam.questions.add(q)

            exam.mistakes = json.dumps(mistakes)
            exam.save()

            # Select a random question for the first one.
            question = get_question(exam_id)

            # Generate the form
            form = ExamForm(question=question.id)

            context = dict()
            context['subject'] = subject
            context['topic'] = question.topic
            context['form'] = form
            context['question'] = question
            context['exam_id'] = exam_id
            context['timer'] = timer
            context['questions_used'] = exam.questions_used.all()
            return render(request, 'choicemaster/exam/resolve_exam.html',

choice_site/choicemaster/templates/choicemaster/exam/configure_exam1.html
{% extends 'choicemaster/base.html' %}

{% block content %}
    <h1>Configure exam</h1>

    <form id="form" action="{% url 'configure_exam1' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
    </form>
{% endblock %}

choice_site/choicemaster/templates/choicemaster/exam/configure_exam2.html
{% extends 'choicemaster/base.html' %}

{% block content %}
    <h1>Configure exam</h1>
    <br>
    <h3><b>SUBJECT:</b> {{ subject_text }}</h3>
    <form id="form" action="{% url 'configure_exam2' exam_id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

choice_site/choicemaster/templates/choicemaster/exam/configure_exam3.html
{% extends 'choicemaster/base.html' %}

{% block content %}
    <h1>Configure exam</h1>
    <br>
    <h3><b>SUBJECT:</b> {{ subject_text }}</h3>
    <h3><b>TOPICS:</b> 
        {% for item in topics %}
                <td>{{ item.topic_title }}</td>
        {% endfor %}
    </h3>
    <form id="form" action="{% url 'configure_exam3' exam_id %}" method="post">
        {% csrf_token %}
        <p>{{ form.quantity.label }}</p>
        <p> {{ form.errors.quantity}} </p>
        <p>{{ form.quantity }}</p>
        <p>{{ form.timer.label }}</p>
        <p> {{ form.errors.timer}} </p>
        <p>{{ form.timer }} {{ form.timer.help_text }}</p>
        <P>{{ form.algorithm.label }} {{ form.algorithm }}</P>
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

choice_site/choicemaster/templates/choicemaster/exam/configure_timer_quantity.html
{% extends 'choicemaster/base.html' %}

{% block content %}
    <h1>Configure your exam</h1>
    <h2>Subject: {{ subject.subject_title }}</h2>
    <h2>Topic: {{ topic.topic_title }}</h2>

    <form action="{% url 'configure_exam' subject.id topic.id %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        
        <p>{{ form }}</p>

        <p><input type="submit" value="Start exam" /></p>
    </form>
{% endblock %}

choice_site/choicemaster/templates/choicemaster/exam/resolve_exam.html
{% extends 'choicemaster/base.html' %}

{% block content %}
    <h2>Evaluation on {{ subject.subject_title }}</h2>
    <h3> Question: {{ question.question_text }}</h3>
    <form action="{% url 'resolve_exam' %}" method="post">
        {% csrf_token %}
        {{ form.answer }}
        <p id="correct_answer_p" style="display: none">
            <b>Correct answer: </b><span id="correct_answer"></span>
        </p>
        <p id="chosen_answer_p" style="display: none">
            <b>Chosen answer: </b><span id="chosen_answer"></span>
        </p>
        <p id="submit"><button type="button" onclick="submit_answer();">Submit</button></p>
        <p id="nextq" style="display: none;"><input type="submit" value="Next"/></p>
        <input type="hidden" name="exam_id" value="{{ exam_id }}">
        <input type="hidden" name="question_id" value="{{ question.id }}">
    </form>
    <div id="question_id" style="display:none">{{ question.id }}</div>

    <button onclick="open_report()"> Same questions?</button>
    <p></p>
    <ul style="display:none" id="IDR">
        {% for quest in questions_used %}
            {% if not forloop.last %}
                 <input onclick="send_r({{ quest.id }}, {{ question.id}})" type="checkbox" id="C{{quest.id}}">{{quest.question_text}}<p></p>
            {% endif %}
        {% endfor %}
    </ul>
    <p></p>
    <button onclick="open_report2()"> Report questions</button>
        <ul style="display:none" id="ID2">
            <p></p>
            Decription <input id="ID3" type="text"name="Edit">
            <button onclick="send_report({{ question.id }})"> Send </button>
        </ul>

    <p></p>
    <div id="timer_div"></div>

    <script type="text/javascript">
        function send_r(id1, id2){
            $.ajax({
                type: "POST",
                url: "/ajax/edit/autoreport/",
                dataType: "json",
                data: {'id1':id1,
                       'id2': id2
                }
             });
            location.reload(false);
        }
       function send_report(idq){
           $.ajax({
                type: "POST",
                url: "/ajax/edit/reporting/",
                dataType: "json",
                data: {'idq':idq ,
                        'description':document.getElementById("ID3").value
                }
            });
           location.reload(false);
       }
        function open_report(){
        var a = document.getElementById("IDR");
        if(a.style.display == "none"){
            a.style.display = "inline";
        }
        else{
            a.style.display = "none";
        }
    }
    function open_report2(){
        var a = document.getElementById("ID2");
        if(a.style.display == "none"){
            a.style.display = "inline";
        }
        else{
            a.style.display = "none";
        }
    }

    //var t_out;

    $(document).ready(function() {
        $('label[for="id_answer_0"]').parent().hide();
        var timer = {{ timer }};
        var seconds_left = timer;
        var time = timer*1000;
        var intervalTimerID = null;
        var iterations = 0;

        intervalTimerID = setInterval(DisplayTimer, 1000);

        function DisplayTimer() {
                ++iterations;
                document.getElementById('timer_div').innerHTML = "You have " + Math.abs(seconds_left-iterations) + " seconds left to answer this question.";
                if (iterations >= seconds_left) {
                    clearInterval(intervalTimerID);
                    intervalTimerID = null;
                    submit_answer();
                    }
            }

        // Reset display for blocks
        $("#correct_answer_p").hide();
        $("#chosen_answer_p").hide();
        $("#id_answer").show();
        $("#submit").show();
        $("#nextq").hide();
    });
    function submit_answer() {
        var val = $('input[name="answer"]:checked').val();
        if (val.length == 0) {
            $("#chosen_answer").text("No answer chosen");
            $("#chosen_answer_p").show();
        }
        console.log("val:", val);
        var e = document.getElementById("question_id").innerHTML;
        var chosenn = $('input[name="answer"]:checked').parent().text();
        //clearTimeout(t_out);
        $.ajax({
            type: 'POST',
            url: '/ajax/get_correct/',
            dataType: 'json',
            data: {'idq': e,
                    'chosen': chosenn},
            success: function(data) {
                // Show correct answer
                $("#correct_answer").text(data['answer']);
                $("#correct_answer_p").show();
                var chosen = $('input[name="answer"]:checked').parent().text();
                $("#chosen_answer").text(chosen);
                $("#chosen_answer_p").show();
                //  Hide answers and show final submit button
                $("#timer_div").hide();
                $("#id_answer").hide();
                $("#submit").hide();
                $("#nextq").show();
                if(data['equal']){
                    document.getElementById("correct_answer_p").style.color = "5FBA7D";
                    document.getElementById("chosen_answer_p").style.color = "5FBA7D";
                }
                else  {
                    document.getElementById("correct_answer_p").style.color = "5FBA7D";
                    document.getElementById("chosen_answer_p").style.color = "DD5F68";
                }

                console.log("test:", data.answer);
                console.log("success!");
            }
        });
    }
    </script>
{% endblock %}