choice_site/choice_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('choicemaster.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
]

choice_site/choicemaster/urls.py
from django.conf.urls import url
from . import views, ajax

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/question/$', views.add_question, name='add_question'),
    url(r'^suggestion/redirect/$', views.redirect_suggestion,
        name='Suggestion'),

    url(r'^report/$', views.report, name='report'),
    url(r'^suggestions/$', views.suggestions, name='suggestions'),

    url(r'ajax/get_quantity_suggestions/$',
        ajax.get_quantity_suggestions,
        name='get_quantity_suggestions'),
    url(r'ajax_view/$', ajax.ajax_view, name='ajax_view'),
    url(r'^ajax/delete/report$', ajax.delete_report, name="delete_report"),
    url(r'^ajax/delete/question/$', ajax.delete_question,
        name="delete_question"),
    url(r'^ajax/delete/answer/$', ajax.delete_answer, name="delete_answer"),
    url(r'^ajax/edit/question/$', ajax.edit_question, name="edit_question"),
    url(r'^ajax/edit/answer/$', ajax.edit_ans, name="edit_answer"),
    url(r'^ajax/get_correct/$', ajax.get_correct, name='get_correct'),
    url(r'^ajax/edit/autoreport/$', ajax.autoreport, name='autoreport'),
    url(r'^ajax/edit/reporting/$', ajax.add_report, name='add_report'),
    url(r'^ajax/edit/correct/$', ajax.edit_correct, name='edit_correct'),
    url(r'^ajax/accept/suggestion/$', ajax.accept_suggestion,
        name='accept_suggestion'),

    url(r'^configure1/$', views.configure_exam1, name='configure_exam1'),
    url(r'^configure2/(?P<exam_id>[0-9]+)/$', views.configure_exam2,
        name='configure_exam2'),
    url(r'^configure3/(?P<exam_id>[0-9]+)/$', views.configure_exam3,
        name='configure_exam3'),

    url(r'^resolve_exam/$', views.resolve_exam, name='resolve_exam'),
    url(r'^resolve_exam/(?P<exam_id>[0-9]+)/$', views.resolve_exam,
        name='resolve_exam'),

    url(r'^statistics/subjects/$', views.subjects_statistics,
        name='subject_statistics'),
    url(r'^statistics/subject/(?P<subject_id>[0-9]+)/$', views.subject_detail,
        name='exam_detail'),
    url(r'^statistics/exam/(?P<exam_id>[0-9]+)/$', views.exam_detail,
        name='exam_detail'),

    url(r'^ajax/suggestion/send/$', ajax.suggestion, name='Send suggestion')
]

choice_site/choicemaster/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class Subject(models.Model):
    subject_title = models.CharField(max_length=40)
    subject_description = models.CharField(max_length=200)
    subject_department = models.CharField(max_length=50)

    def __unicode__(self):
        """
        Method to show the correct object name in the admin interface.
        """
        return self.subject_title


class Topic(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    topic_title = models.CharField(max_length=40)
    topic_description = models.CharField(max_length=200)

    def __unicode__(self):
        """
        Method to show the correct object name in the admin interface.
        """
        return self.topic_title


class Question(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    available = models.BooleanField(default=False)

    def __unicode__(self):
        """
        Method to show the correct object name in the admin interface.
        """
        return self.question_text


class Exam(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, default=0)
    exam_quantity_questions = models.IntegerField(default=0)
    exam_timer = models.IntegerField(default=60)
    exam_algorithm = models.CharField(max_length=200, default=0)
    exam_result = models.FloatField(default=0)
    topic = models.ManyToManyField(Topic)
    questions = models.ManyToManyField(Question, related_name="questions")
    questions_used = models.ManyToManyField(Question, related_name="used")
    remaining = models.IntegerField(default=0)
    mistakes = models.TextField(null=True, default='{}')
    closed = models.BooleanField(default=False)
    # JSON - serialized (text) version of the list
    amount_correct = models.IntegerField(default=0)
    passing_score = models.FloatField(default=0.6)
    passed = models.BooleanField(default=False)

    def __unicode__(self):
        """
        Method to show the correct object name in the admin interface.
        """
        return self.user.username + ' - ' + self.subject.subject_title


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)

    def __unicode__(self):
        """
        Method to show the correct object name in the admin interface.
        """
        return self.answer_text


class Report(models.Model):
    NOT_EVALUATED = 'NE'
    IN_EVALUATION = 'IE'
    EVALUATED = 'E'
    STATE_CHOICES = (
        (NOT_EVALUATED, 'Not evaluated'),
        (IN_EVALUATION, 'In evaluation'),
        (EVALUATED, 'Evaluated'),
    )

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    report_state = models.CharField(max_length=2, choices=STATE_CHOICES,
                                    default=NOT_EVALUATED)
    report_description = models.CharField(max_length=200)

    def __unicode__(self):
        """
        Method to show the correct object name in the admin interface.
        """
        return self.question.question_text

choice_site/choicemaster/views.py
import sys
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from choicemaster import models
from .forms import *
from django.http.response import HttpResponse
from .upload import parse_xml_question
from .exam_functions import get_question, get_mistakes
from .models import Report, Question, Answer, Subject
from graphos.sources.simple import SimpleDataSource
from graphos.renderers.gchart import LineChart
import json


@login_required
def index(request, message=''):
    """
    Simple index view that renders a message passed by some request and
    returns it as a HTML response
    :param request: Request, str
    :return: View
    """
    if message:
        context = {'message': message}
    else:
        context = {'message': 'Everything ok!'}
    context['reported'] = Report.objects.exclude(report_state='E').count()

    return render(request, 'choicemaster/index.html', context)


def redirect_suggestion(request):
    context = {'message': 'Suggestion submitted successfully'}
    return render(request, 'choicemaster/index.html', context)


@login_required
def add_question(request):
    """
    Get the list of available subjects from request and return them rendered
    as a response with the corresponding template
    :param request: Request
    :return: View
    """
    context = dict()
    if request.user.is_staff:
        if request.method == 'POST':
            form = UploadQuestionForm(request.POST, request.FILES)
            # if form.is_valid():
            topic = request.POST.get('topic')
            file = request.FILES['xmlfile']
            if topic > 0:
                result = parse_xml_question(file, topic)
                if result['status']:
                    return redirect('index')
                else:
                    form = UploadQuestionForm()
        else:
            form = UploadQuestionForm()
            context['form'] = form

        return render(request, 'choicemaster/add/question.html', context)

    else:
        form = SuggestQuestionForm()
        context['form'] = form
        return render(request, 'choicemaster/add/suggestion.html', context)


def report(request):
    """
    Pass on to the reports template, the number of reports not evaluated so far
    :param request: Request
    :return: View
    """
    context = dict()
    context['reports'] = Report.objects.exclude(report_state="E")
    return render(request, 'choicemaster/report.html', context)


def suggestions(request):
    """
    Pass on to the suggested questions template, the number of questions
    suggested so far
    :param request: Request
    :return: View
    """
    context = dict()
    context['questions'] = models.Question.objects.filter(available=False)
    return render(request, 'choicemaster/suggestions.html', context)


# Nuevos configure
@login_required
def configure_exam1(request):
    """
    First view regarding an exam configuration. Look for a form from the input
    request. Retrieve the subject from the POST data and create an exam
    instance related to the user to redirect it to the template in which he
    chooses the topics he wants to include in the exam
    :param request: Request
    :return: View
    """
    if request.method == 'POST':
        user = None
        if request.user.is_authenticated():
            user = request.user
        form = SubjectForm(request.POST)
        if form.is_valid():
            subject_id = request.POST.get('subject')
            exam = models.Exam(user=user)
            exam.subject = models.Subject.objects.get(pk=subject_id)
            exam.save()
            return redirect('configure_exam2', exam_id=exam.id)
    else:
        form = SubjectForm()
        return render(request, 'choicemaster/exam/configure_exam1.html',
                      {'form': form})


@login_required
def configure_exam2(request, exam_id):
    """
    Get a list of topics from request and include them in the exam given by
    exam_id. Save it in the exam object and redirect it to the next exam
    configuration template
    :param request: Request, str
    :return: View
    """
    e = models.Exam.objects.get(pk=exam_id)
    if not e.closed:
        ids = e.subject.id
        context = dict()
        context['subject_text'] = e.subject.subject_title
        context['exam_id'] = exam_id
        if request.method == 'POST':
            form = MultipleTopicForm(ids, request.POST)
            if form.is_valid():
                topic_ids = request.POST.getlist('topic')
                for idt in topic_ids:
                    t = models.Topic.objects.get(pk=idt)
                    e.topic.add(t)
                e.save()
                return redirect('configure_exam3', exam_id=exam_id)
        else:
            form = MultipleTopicForm(e.subject.id)

        context['form'] = form
        return render(
            request,
            'choicemaster/exam/configure_exam2.html',
            context)
    else:
        message = "You have already taken that exam." \
            + "Please create a new one from the 'Take an exam' section"
        return render(request, 'choicemaster/index.html', {'message': message})


@login_required
def configure_exam3(request, exam_id):
    """
    Add questions to the exam object according to the number required by the
    user. Raise an error message in case the required number of questions is
    greater than the number of questions available in the database for such
    subject
    :param request: Request, str
    :return: View
    """
    e = models.Exam.objects.get(pk=exam_id)
    if not e.closed:
        max_quantity = 0
        context = dict()
        context['subject_text'] = e.subject.subject_title
        context['exam_id'] = exam_id
        context['topics'] = e.topic.all()

        for t in e.topic.all():
            questions = models.Question.objects.filter(
                topic=t.id, available=True)
            max_quantity += len(questions)
        if request.method == 'POST':
            form = ConfigForm(max_quantity, request.POST)
            if form.is_valid():
                quantity = request.POST.get('quantity')
                timer = request.POST.get('timer')
                algorithm = request.POST.get('algorithm')
                e = models.Exam.objects.get(pk=exam_id)
                e.exam_quantity_questions = quantity
                e.remaining = quantity
                e.exam_timer = timer
                e.exam_algorithm = algorithm
                e.save()
                return redirect('resolve_exam', exam_id=exam_id)
        else:
            if max_quantity > 0:
                form = ConfigForm(max_quantity)
                context['form'] = form
                return render(
                    request,
                    'choicemaster/exam/configure_exam3.html',
                    context)
            else:
                message = "Sorry there are not questions about those topics" \
                          "yet! We invite you to suggest some on the Suggest" \
                          " a question section"
                return render(request,
                              'choicemaster/index.html',
                              {'message': message})

    else:
        message = "You have already taken that exam." \
            + " Please create a new one from the 'Take an exam' section"
        return render(request, 'choicemaster/index.html', {'message': message})


def get_first(iterable, default=None):
    if iterable:
        for item in iterable:
            return item
    return default


def resolve_exam(request, exam_id=''):
    """
    View to actually solve the exam. Consider two cases:
    1. request has been sent for the first time on this exam, in which case it
    contains the information about the exam settings (subject, timer, quantity,
    algorithm). Generate an ExamView for such settings, fill the exam object
    with questions and then choose the first question from the first topic in
    order to display it in the resolve_exam template

    2. request method is POST, which means it has been triggered by a solution
    submitted in the front end. Check whether the answer given by the user is
    right or wrong to keep a record to be used in the algorithm to display
    questions afterwards. Also, keep track of remaining time and use it to pass
    to the next question in case it is over.
    :param request: Request, str
    :return: View
    """
    if request.method != 'POST':
        exam = models.Exam.objects.get(pk=exam_id)
        if not exam.closed:
            subject = exam.subject
            timer = exam.exam_timer
            algorithm = exam.exam_algorithm
            topic_ids = exam.topic.all()  # TODO
            mistakes = {}
            # We store all the questions of the selected topics
            for item in topic_ids:
                questions_tmp = models.Question.objects.filter(
                    topic=models.Topic
                    .objects
                    .get(pk=item.id),
                    available=True)
                mistakes[str(item.id)] = 0
                for q in questions_tmp:
                    exam.questions.add(q)

            exam.mistakes = json.dumps(mistakes)
            exam.save()

            # Select a random question for the first one.
            question = get_question(exam_id)

            # Generate the form
            form = ExamForm(question=question.id)

            context = dict()
            context['subject'] = subject
            context['topic'] = question.topic
            context['form'] = form
            context['question'] = question
            context['exam_id'] = exam_id
            context['timer'] = timer
            context['questions_used'] = exam.questions_used.all()
            return render(request, 'choicemaster/exam/resolve_exam.html',

choice_site/choicemaster/templates/choicemaster/add/question.html
{% extends 'choicemaster/base.html' %}

{% block content %}
    <h1>Add questions</h1>
    <form id="question_form" action="{% url 'add_question' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p> {{ form.subject }} </p>
        <p> {{ form.topic }} </p>
        <p> {{ form.xmlfile.label }} </p>
        <p> {{ form.xmlfile }} </p>
        <br>
        <input type="submit" value="Submit" />
    </form>

    <script type="text/javascript">
    $(document).ready(function() {
        $('option[value=""]').text("Select subject");
    });

    function get_topics() {
        var frm = $('#subject_form');
        var e = document.getElementById("id_subject");
        var ids = e.value;
        console.log("ids =", ids);
        $.ajax({
            type: 'POST',
            url: '/ajax_view/',
            dataType: 'json',
            data: {'ids': ids},
            success: function(data) {
                var topics = data.topics;
                console.log("topics:", topics);
                $('#id_topic').html(topics);
                console.log("success!");
            }
        });
    }
    </script>


{% endblock %}

choice_site/choicemaster/templates/choicemaster/add/suggestion.html
{% extends 'choicemaster/base.html' %}

{% block content %}
    {% load static %}

    <script>
        var i = 0;
        function add_ans() {
            if(i<10) {
                i += 1;
                document.getElementById("bool").innerHTML += '<span style="padding-right: 5px;">Add answer</span>';
                var x = document.createElement("INPUT");
                x.setAttribute("type", "text");
                x.setAttribute("id", "value" + String(i));
                x.setAttribute("class", "value");
                x.setAttribute("display", "inline");
                x.setAttribute("margin-left", "40px");
                x.setAttribute("margin-right", "40px");
                document.getElementById("bool").appendChild(x);
                document.getElementById("bool").innerHTML += '<span style="padding-right: 5px; style="padding-left: 5px;">  Correct?</span>';
                var y = document.createElement("INPUT");
                y.setAttribute("type", "radio");
                y.setAttribute("name", "add");
                y.setAttribute("display", "inline");
                y.setAttribute("class", "correct");
                y.setAttribute("id", "correct" + String(i));
                document.getElementById("bool").appendChild(y);
                document.getElementById("bool").innerHTML += '<br> </br>';
            }
        }

        function send_question() {
            var j = 0;
            var k = 0;
            var lst = [];
            var correct = -1;
            var question = document.getElementById("question").value;
            var topic = document.getElementById("id_topic").value;
            var values = document.getElementById("bool").querySelectorAll(".value");
            var x = document.getElementById("bool").querySelectorAll(".correct");
            for (j; j < i; j++) {
                var text = values[j].value;
                if (text && (text.length != 0)) {
                   lst.push(text);
                   k +=1;
                   if(x[j].checked){
                        correct = j;
                    }
               }
            }
            if (k < 1 || correct == -1 || question.length == 0) {
                alert("Error sending question");
            } else {
                var jsonText = JSON.stringify(lst);
                $.ajax({
                    type: "POST",
                    url: "/ajax/suggestion/send/",
                    dataType: "json",
                    data: {'lst': jsonText , 'correct': correct,
                        'question': question, 'topic': topic},
                    success: function(data) {
                        console.log("Iegamos");
                        if (data['status'] == false) {
                            console.log("entro como papa");
                            window.location.href = "/suggestion/redirect/";
                        } else {
                            document.getElementById("messages").value =
                                "Question already present in database"
                        }
                    }
                });
                 window.location.href = "/suggestion/redirect/";
            }
        }

    function get_topics() {
        var frm = $('#subject_form');
        var e = document.getElementById("id_subject");
        var ids = e.value;
        console.log("ids =", ids);
        $.ajax({
            type: 'POST',
            url: '/ajax_view/',
            dataType: 'json',
            data: {'ids': ids},
            success: function(data) {
                var topics = data.topics;
                console.log("topics:", topics);
                $('#id_topic').html(topics);
                console.log("success!");
            }
        });
    }
    </script>

    <h1>Suggest question</h1>
    <br>
    <h3>Select the subject:</h3>
    <p>{{ form.subject }}</p>
    <h3>Select the topic:</h3>
    <p>{{ form.topic }}</p>
    <br>
    <label class="medium-text">Question<br><input style="padding-left: 10px" type="text" required="" id="question"></label>
    <br>
    <span class="medium-text" style="padding-right: 50px;"><b>Answers</b></span>
    <br>
    <span class="light" style="padding-left: 20px">Add <img src="{% static 'add.png' %}" onclick="add_ans()" height="20"  width="20"></span>
    <br>
    <div id="bool" style="display: inline"></div>
    <br>
    <span class="light medium-text" style="padding-left: 20px;">Send <img src="{% static 'send.png' %}" height="40" width="40" onclick="send_question()"></span>
{% endblock %}